### PR TITLE
Publish Rust documentation to http://tessel.github.io/tessel-rust/

### PR DESCRIPTION
**Pull request by tcr**
It's customary for Cargo-generated documentation to be associated with the Github repository. Github Pages recently changed, so the option is to add it to this repository in the docs/ page.
- Adds about 1mb to the repo size. This is a one-shot thing, most files will be unchanged with new generated documentation.
- If Crates.io finally adds documentation hosting (or Github allows a branch again), it's easy to strip the docs/ folder from the repo history using filter-branch.
- Standard Cargo docs that can eventually be merged into docs.tessel.io

### CODE REVIEW

**Comment by johnnyman727** [comment]
Sure, looks fine to me. How of curiosity, did you generate this with `rustdoc`? What options did you use?

**Comment by tcr** [comment]
@johnnyman727 I did the following:
- Ran `cargo doc` in the root directory.
- Moved `target/doc` to `docs`.
- Created the `docs/index.html` file in this repo to automatically redirect (which I think will work, will see when it gets posted to Github...)

**Comment by kevinmehall** [comment]
[You can still use gh-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#default-source-settings-for-repositories-without-the-username-naming-scheme)

**Comment by tcr** [comment]
That's really good to hear. They could've mentioned that in the control panel...

Even better, [docs.rs](docs.rs) _just_ went live. So that seems like the obvious choice.

**Pull request merged**
