### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by johnnyman727**

### CODE REVIEW

**Comment by johnnyman727** [comment]
@cflewis I'm trying to add some CI to the repo. Unfortunately, Travis was failing if I use Rust v1.5.0 but passed if I use Rust v1.8.0 or later. We need to use Rust v.1.5.0 because that's the version of the Rust toolchain we're using in the cross compiler. The failure point is [actually with `tempfile`](https://travis-ci.org/tessel/tessel-rust/builds/144461571).

**Comment by cflewis** [comment]
Can the cross compiler be updated? v.1.5.0 is pretty old now.

The test could be rewritten without `try_clone()` but I'd rather investigate updating the cross compiler first.

**Comment by johnnyman727** [comment]
Yes, probably. We'll just need to [update the `1.5.0` references here](https://github.com/tessel/rust-compilation-server/blob/master/Dockerfile#L19-L25) and make sure it still compiles properly. I have not test it yet (currently trying to get the server running on a digital ocean droplet).

**Comment by johnnyman727** [comment]
@cflewis I tried to upgrade to 1.9.0 but hit a roadblock: https://github.com/tessel/rust-compilation-server/pull/7

I haven't investigated much yet but let me know if you might see the cause.

**Comment by cflewis** [comment]
No idea 😞

**Comment by cflewis** [comment]
What if you go all the way to 1.11?

**Comment by rwaldron** [comment]
I like where this is going :)

**Comment by johnnyman727** [comment]
:rabbit:hole

**Comment by rwaldron** [comment]
@johnnyman727 Oh, I just meant that I like the appearance of a ".travis.yml" in this project :)

**Comment by johnnyman727** [comment]
We can target Rust 1.10.0 now with https://github.com/tessel/rust-compilation-server/pull/9.

**Pull request merged**
